CREATE TABLE [LTBI].[EligiblePatientData](
	[Flag4FileName] [varchar](255) NOT NULL,
	[HasPatientRecord] [bit] NOT NULL,
	[RecordNo] [int] NOT NULL,
	[TestReason] [varchar](255) NULL,
	[SICBCode] [varchar](255) NULL,
	[SICBName] [varchar](255) NULL,
	[CurrGPCode] [varchar](255) NULL,
	[CurrGPName] [varchar](255) NULL,
	[CurrGPRegDate] [date] NULL,
	[Flag4GPCode] [varchar](255) NULL,
	[Flag4GPName] [varchar](255) NULL,
	[Flag4GPRegDate] [date] NULL,
	[NHSNumber] [varchar](255) NOT NULL,
	[GivenName] [varchar](255) NOT NULL,
	[FamilyName] [varchar](255) NOT NULL,
	[Gender] [varchar](255) NOT NULL,
	[DOB] [date] NOT NULL,
	[COB] [varchar](255) NOT NULL,
	[UKEntDate] [date] NOT NULL,
	[AddrLine1] [varchar](500) NULL,
	[AddrLine2] [varchar](500) NULL,
	[AddrLine3] [varchar](255) NULL,
	[AddrLine4] [varchar](255) NULL,
	[FullAddress] [varchar](1000) NULL,
	[AddrPcode] [varchar](255) NOT NULL,
	[TelNo] [varchar](255) NULL,
	[MobTelNo] [varchar](255) NULL,
	[EmailAddr] [varchar](255) NULL,
	[ICBFromSICB] [varchar](10) NULL,
	[ICBFromCurrGP] [varchar](10) NULL,
	[ICBFromFlag4GP] [varchar](10) NULL,
	[ICBFromPcode] [varchar](10)  NULL
)
