CREATE TABLE [LTBI].[LTBIBulkUploadTestingandTreatment]
(
[PatID] [int] NOT NULL,
	[ICBCode] [char](9) NOT NULL,
	[ICBName] [nvarchar](255) NOT NULL,
	[SICBCode] [char](9)  NULL,
	[SICBName] [nvarchar](255)  NULL,
	[NHSNumber] [char](10) NOT NULL,
	[GivenName] [varchar](100) NOT NULL,
	[FamilyName] [varchar](100) NOT NULL,
	[DateOfBirth] [date] NULL,
	[Gender] [varchar](32) NULL,
	[PatientPostcode] [varchar](8) NOT NULL,
	[GPCode] [char](9) NULL,
	[GPPracticeName] [varchar](255) NULL,
	[CountryOfBirth] [varchar](100) NULL,
	[Ethnicity] [varchar](50) NULL,
	[UKEntryDay] [tinyint] NULL,
	[UKEntryMonth] [tinyint] NULL,
	[UKEntryYear] [smallint] NULL,
	[UKEntryDate] VARCHAR(20) NULL,
	[CountryofTravel] [varchar](100) NULL,
	[SymptomsindicativeofTB] [varchar](3) NULL,
	[PreviousactiveTB] [varchar](3) NULL,
	[PreviouslatentTB] [varchar](3) NULL,
	[DateofIGRAtestfirstinvitation] [date] NULL,
	[IGRAtestfirstinvitationmethod] [varchar](41) NULL,
	[DateofIGRAtestsecondinvitation] [date] NULL,
	[IGRAtestsecondinvitationmethod] [varchar](41) NULL,
	[DateofIGRAtestthirdinvitation] [date] NULL,
	[IGRAtestthirdinvitationmethod] [varchar](41) NULL,
	[Testaccepted] [varchar](3) NULL,
	[Testnotaccepteddate] [date] NULL,
	[Testnotacceptedreason] [varchar](4000) NULL,
	[Testcarriedoutdate] [date] NULL,
	[LTBItestresult] [varchar](4000) NULL,
	[Counsellingreferraldate] [date] NULL,
	[Treatmentreferraldate] [date] NULL,
	[Treatmentnotreferredreason] [varchar](4000) NULL,
	[TreatmentnotreferredreasonOther] [varchar](100) NULL,
	[Chestxrayresult] [varchar](4000) NULL,
	[Chestxrayresultdate] [date] NULL,
	[AssessedforactiveTB] [varchar](3) NULL,
	[Treatmentdecisiondate] [date] NULL,
	[Patienttreatmentdecision] [varchar](100) NULL,
	[Treatmentnotacceptedreason] [varchar](4000) NULL,
	[Treatmentdeferredreason] [varchar](4000) NULL,
	[TreatmentdeferredreasonOther] [nvarchar](4000) NULL,
	[LTBItreatmentstarted] [varchar](3) NULL,
	[LTBItreatmentstartdate] [date] NULL,
	[LTBItreatmentprescribed] [varchar](4000) NULL,
	[LTBItreatmentcompleted] [varchar](19) NULL,
	[LTBItreatmentcompletiondate] [date] NULL,
	[LTBIdatetreatmentstopped] [date] NULL,
	[ReasonLTBItreatmentstopped] [varchar](4000) NULL,
	[Adversereactiontomedication] [varchar](3) NULL,
	[Sideeffects] [varchar](8000) NULL,
	DataRefreshedAt DATETIME NOT NULL DEFAULT GETDATE()
)