CREATE TABLE [dbo].[LegacyExtract]
(
	[LegacyExtractId] [int] IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[NotificationId] [int] NOT NULL,
	[SourceSystem] [nvarchar](50) NOT NULL,
	[LocalPatientId] [nvarchar](50) NULL,
	[AddressLine1] [nvarchar](255) NULL,
	[AddressLine2] [nvarchar](255) NULL,
	[Town] [nvarchar](255) NULL,
	[County] [nvarchar](255) NULL,
	[PCT] [nvarchar] (60) NULL,
	[HPU] [nvarchar] (60) NULL,
	[SitePulmonary] [varchar](5) NULL,
	[SiteBoneSpine] [varchar](5) NULL,
	[SiteBoneOther] [varchar](5) NULL,
	[SiteCNSMeningitis] [varchar](5) NULL,
	[SiteCNSOther] [varchar](5) NULL,
	[SiteCryptic] [varchar](5) NULL,
	[SiteGI] [varchar](5) NULL,
	[SiteGU] [varchar](5) NULL,
	[SiteITLymphNodes] [varchar](5) NULL,
	[SiteLymphNode] [varchar](5) NULL,
	[SiteLaryngeal] [varchar](5) NULL,
	[SiteMiliary] [varchar](5) NULL,
	[SitePleural] [varchar](5) NULL,
	[SiteNonPulmonaryOther] [varchar](5) NULL,
	[SiteNonPulmonaryUnknown] [varchar](5) NULL,
	[OtherExtraPulmonarySite] [nvarchar](255) NULL,
	[SiteUnknown] [varchar](5) NULL,
	[BcgVaccinationDate] [varchar](20) NULL,
	[DOT] [nvarchar](10) NULL,
	[InPatient] [nvarchar](10) NULL,
	[Comments] [nvarchar](500) NULL,
	[TreatmentHPU] [nvarchar](255) NULL,
	[HospitalPCT] [nvarchar](255) NULL,
	[HospitalLocalAuthority] [nvarchar](255) NULL,
	[ResolvedResidenceHPU] [nvarchar](100) NULL,
	[HIVTestOffered] [nvarchar](255) NULL,
	[ProposedDrugRegimen] [nvarchar](1000) NULL,
	[OtherImmunosuppressionComments] [nvarchar](50) NULL,
	[WorldRegionName] [nvarchar](50) NULL
)  
