CREATE TABLE [dbo].[LegacyLabExtract]
(
	[LegacyExtractId] [int] IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[NtbsId] [int] NULL,
	[EtsId] [int] NULL,
	[SourceSystem] [nvarchar](50) NOT NULL,
	[IDOriginal] [nvarchar](50) NULL,
	[Source] [varchar](8) NOT NULL,
	[LaboratoryTestType] [nvarchar](255) NULL,
	[Specimen] [nvarchar](255) NULL,
	[SpecimenDate] [datetime] NULL,
	[Result] [varchar](9) NULL,
	[Species] [nvarchar](255) NULL,
	[SourceLabName] [nvarchar](65) NULL,
	[PatientId] [nvarchar](50) NULL,
	[OpieID] [nvarchar](36) NULL,
	[Isoniazid] [varchar](1) NULL,
	[Rifampicin] [varchar](1) NULL,
	[Ethambutol] [varchar](1) NULL,
	[Pyrazinamide] [varchar](1) NULL,
	[Streptomycin] [varchar](1) NULL,
	[Amikacin] [varchar](1) NULL,
	[Azithromycin] [varchar](1) NULL,
	[Capreomycin] [varchar](1) NULL,
	[Ciprofloxacin] [varchar](1) NULL,
	[Clarithromycin] [varchar](1) NULL,
	[Clofazimine] [varchar](1) NULL,
	[Cycloserine] [varchar](1) NULL,
	[Ethionamide] [varchar](1) NULL,
	[PAS] [varchar](1) NULL,
	[Prothionamide] [varchar](1) NULL,
	[Rifabutin] [varchar](1) NULL,
	[Moxifloxacin] [varchar](1) NULL,
	[Ofloxacin] [varchar](1) NULL,
	[Kanamycin] [varchar](1) NULL,
	[Linezolid] [varchar](1) NULL,
	[ReferenceLaboratory] [nvarchar](65) NULL,
	[ReferenceLaboratoryNumber] [nvarchar](50) NULL,
	[SourceLaboratoryNumber] [nvarchar](50) NULL,
	[StrainType] [nvarchar](50) NULL,
	[Comments] [nvarchar](max) NULL,
	[MatchType] [nvarchar](30) NULL
	
)
