CREATE TABLE [dbo].[LegacyExtract]
(
	[LegacyExtractId] [int] IDENTITY(1,1) NOT NULL PRIMARY KEY,
	-- Global NotificationId
	[NotificationId] [int] NOT NULL,
	[NtbsId] [int] NULL,
	[EtsId] [int] NULL,
	[SourceSystem] [nvarchar](50) NOT NULL,
	[IDOriginal] [nvarchar](50) NULL,
	[LocalPatientId] [nvarchar](255) NULL,
	[CaseReportDate] [date] NULL,
	[ReportYear] [nvarchar](4) NULL,
	[Denotified] [varchar](3) NULL,
	[DenotificationDate] [date] NULL,
	[DenotificationComments] [nvarchar](255) NULL,
	[CaseManager] [nvarchar](255) NULL,
	[Hospital] [nvarchar](255) NULL,
	[PatientsConsultant] [nvarchar](255) NULL,
	[Title] [nvarchar](255) NULL,
	[Forename] [nvarchar](50) NULL,
	[Surname] [nvarchar](50) NULL,
	[NHSNumber] [nvarchar](50) NULL,
	[Sex] [varchar](1) NULL,
	[Age] [tinyint] NULL,
	[DateOfBirth] [nvarchar](10) NULL,
	[AddressLine1] [nvarchar](255) NULL,
	[AddressLine2] [nvarchar](255) NULL,
	[Town] [nvarchar](255) NULL,
	[County] [nvarchar](255) NULL,
	[Postcode] [nvarchar](10) NULL,
	[PCT] [nvarchar] (60) NULL,
	[HPU] [nvarchar] (60) NULL,
	[LocalAuthority] [nvarchar](255) NULL,
	[Region] [nvarchar](60) NULL,
	[Occupation] [nvarchar](255) NULL,
	[OccupationCategory] [nvarchar](255) NULL,
	[EthnicGroup] [nvarchar](255) NULL,
	[UKBorn] [varchar](9) NULL,
	[BirthCountry] [nvarchar](255) NULL,
	[UKEntryYear] [int] NULL,
	[SymptomOnset] [nvarchar](10) NULL,
	[StartOfTreatment] [nvarchar](10) NULL,
	[DateOfDiagnosis] [nvarchar](10) NULL,
	[DatePresented] [nvarchar](10) NULL,
	[SitePulmonary] [varchar](5) NULL,
	[SiteBoneSpine] [varchar](5) NULL,
	[SiteBoneOther] [varchar](5) NULL,
	[SiteCNSMeningitis] [varchar](5) NULL,
	[SiteCNSOther] [varchar](5) NULL,
	[SiteCryptic] [varchar](5) NULL,
	[SiteGI] [varchar](5) NULL,
	[SiteGU] [varchar](5) NULL,
	[SiteITLymphNodes] [varchar](5) NULL,
	[SiteLymphNode] [varchar](5) NULL,
	[SiteLaryngeal] [varchar](5) NULL,
	[SiteMiliary] [varchar](5) NULL,
	[SitePleural] [varchar](5) NULL,
	[SiteNonPulmonaryOther] [varchar](5) NULL,
	[SiteNonPulmonaryUnknown] [varchar](5) NULL,
	[OtherExtraPulmonarySite] [nvarchar](255) NULL,
	[SiteUnknown] [varchar](5) NULL,
	[PreviouslyDiagnosed] [nvarchar](10) NULL,
	[YearsSinceDiagnosis] [tinyint] NULL,
	[PreviouslyTreated] [nvarchar](10) NULL,
	[TreatmentInUK] [nvarchar](10) NULL,
	[PreviousId] [nvarchar](50) NULL,
	[BcgVaccinated] [varchar](9) NULL,
	[BcgVaccinationDate] [varchar](20) NULL,
	[DrugUse] [nvarchar](10) NULL,
	[AlcoholUse] [nvarchar](10) NULL,
	[Homeless] [nvarchar](10) NULL,
	[Prison][nvarchar](10) NULL,
	[PostMortemDiagnosis] [varchar](3) NOT NULL,
	[PostMortemDeathDate] [nvarchar](10) NULL,
	[DidNotStartTreatment] [nvarchar](10) NULL,
	[MDRTreatment] [nvarchar](10) NULL,
	[MDRTreatmentDate] [nvarchar](10) NULL,
	[ShortCourse] [nvarchar](10) NULL,
	[DOT] [nvarchar](10) NULL,
	[InPatient] [nvarchar](10) NULL,
	[Comments] [nvarchar](max) NULL,
	[TOMTreatmentInterruptedReason] [varchar](150) NULL,
	[TOMTreatmentChangedReason] [varchar](150) NULL,
	[TOMCompleteCourse] [varchar](255) NULL,
	[TOMIncompleteReason] [varchar](255) NULL,
	[TOMSubmittedDate] [nvarchar](10) NULL,
	[TOMFollowUpResult] [varchar](150) NULL,
	[TOMDeathDate] [nvarchar](10) NULL,
	[TOMDeathRelationship] [nvarchar](255) NULL,
	[TOMEndOfTreatmentDate] [nvarchar](10) NULL,
	[TOMTreatmentRegimen] [varchar](150) NULL,
	[TOMNonTuberculousMycobacteria] [varchar](500) NULL,
	[TOMConversion] [varchar](24) NULL,
	[TOMComment] [nvarchar](500) NULL,
	[TOMReasonExceeds12mths] [nvarchar](50) NULL,
	[TOMReported12mth] [nvarchar](10) NULL,
	[TOMTreatmentInterruptedReason24mth] [nvarchar](150) NULL,
	[TOMTreatmentChangedReason24mth] [nvarchar](150) NULL,
	[TOMCompleteCourse24mth] [nvarchar](150) NULL,
	[TOMIncompleteReason24mth] [nvarchar](255) NULL,
	[TOMSubmittedDate24mth] [nvarchar](10) NULL,
	[TOMFollowUpResult24mth] [nvarchar](255) NULL,
	[TOMDeathDate24mth] [nvarchar](10) NULL,
	[TOMDeathRelationship24mth] [nvarchar](255) NULL,
	[TOMEndOfTreatmentDate24mth] [nvarchar](10) NULL,
	[TOMTreatmentRegimen24mth] [nvarchar](150) NULL,
	[TOMNonTuberculousMycobacteria24mth] [nvarchar](500) NULL,
	[TOMConversion24mth] [nvarchar](24) NULL,
	[TOMComment24mth] [nvarchar](500) NULL,
	[TOMReported24mth] [nvarchar](10) NULL,
	[TreatmentRegion] [nvarchar](255) NULL,
	[TreatmentHPU] [nvarchar](255) NULL,
	[HospitalName] [nvarchar](255) NULL,
	[HospitalPCT] [nvarchar](255) NULL,
	[HospitalLocalAuthority] [nvarchar](255) NULL,
	[ResolvedResidenceHPU] [nvarchar](100) NULL,
	[ResolvedResidenceRegion] [nvarchar](100) NULL,
	[ResolvedResidenceLA] [nvarchar](100) NULL,
	[NoFixedAbode] [bit] NULL,
	[HIVTestOffered] [nvarchar](255) NULL,
	[NoSampleTaken] [bit] NULL,
	[ProposedDrugRegimen] [nvarchar](1000) NULL,
	[CurrentDrugUse] [nvarchar](10) NULL,
	[DrugUseLast5Years] [nvarchar](10) NULL,
	[DrugUseMoreThan5YearsAgo] [nvarchar](10) NULL,
	[CurrentlyHomeless] [nvarchar](10) NULL,
	[HomelessLast5Years] [nvarchar](10) NULL,
	[HomelessMoreThan5YearsAgo] [nvarchar](10) NULL,
	[CurrentlyInprisonOrWhenFirstSeen] [nvarchar](10) NULL,
	[PrisonLast5Years] [nvarchar](10) NULL,
	[PrisonAbroadLast5Years] [nvarchar](10) NULL,
	[PrisonMoreThan5YearsAgo] [nvarchar](10) NULL,
	[PrisonAbroadMoreThan5YearsAgo] [nvarchar](10) NULL,
	[TravelledOutsideUK] [nvarchar](10) NULL,
	[ToHowManyCountries] [nvarchar](5) NULL,
	[TravelCountry1] [nvarchar](50) NULL,
	[DurationofTravel1(Months)] [nvarchar](10) NULL,
	[TravelCountry2] [nvarchar](50) NULL,
	[DurationofTravel2(Months)] [nvarchar](10) NULL,
	[TravelCountry3] [nvarchar](50) NULL,
	[DurationofTravel3(Months)] [nvarchar](10) NULL,
	[ReceivedVisitors] [nvarchar](10) NULL,
	[FromHowManyCountries] [nvarchar](5) NULL,
	[VisitorCountry1] [nvarchar](50) NULL,
	[DurationVisitorsStayed1] [nvarchar](25) NULL,
	[VisitorCountry2] [nvarchar](50) NULL,
	[DurationVisitorsStayed2] [nvarchar](25) NULL,
	[VisitorCountry3] [nvarchar](50) NULL,
	[DurationVisitorsStayed3] [nvarchar](25) NULL,
	[Diabetes] [nvarchar](10) NULL,
	[HepB] [nvarchar](10) NULL,
	[HepC] [nvarchar](10) NULL,
	[ChronicLiverDisease] [nvarchar](10) NULL,
	[ChronicRenalDisease] [nvarchar](10) NULL,
	[ImmunoSuppression] [nvarchar](10) NULL,
	[BiologicalTherapy] [nvarchar](10) NULL,
	[Transplantation] [nchar](10) NULL,
	[ImmunosuppressionOther] [nvarchar](10) NULL,
	[ImmunosuppressionComments] [nvarchar](50) NULL,
	[CurrentSmoker] [nvarchar](10) NULL,
	[AdultContactsIdentified] [nvarchar] (5) NULL,
	[ChildContactsIdentified] [nvarchar] (5) NULL,
	[TotalContactsIdentified] [nvarchar] (5) NULL,
	[AdultContactsAssessed] [nvarchar] (5) NULL,
	[ChildContactsAssessed] [nvarchar] (5) NULL,
	[TotalContactsAssessed] [nvarchar] (5) NULL,
	[AdultContactsActiveTB] [nvarchar] (5) NULL,
	[ChildContactsActiveTB] [nvarchar] (5) NULL,
	[TotalContactsActiveTB] [nvarchar] (5) NULL,
	[AdultContactsLTBI] [nvarchar] (5) NULL,
	[ChildContactsLTBI] [nvarchar] (5) NULL,
	[TotalContactsLTBI] [nvarchar] (5) NULL,
	[AdultContactsLTBITreat] [nvarchar] (5) NULL,
	[ChildContactsLTBITreat] [nvarchar] (5) NULL,
	[TotalContactsLTBITreat] [nvarchar] (5) NULL,
	[AdultContactsLTBITreatComplete] [nvarchar] (5) NULL,
	[ChildContactsLTBITreatComplete] [nvarchar] (5) NULL,
	[TotalContactsLTBITreatComplete] [nvarchar] (5) NULL,
	[TOMTreatmentInterruptedReason36mth] [nvarchar](150) NULL,
	[TOMTreatmentChangedReason36mth] [nvarchar](150) NULL,
	[TOMCompleteCourse36mth] [nvarchar](150) NULL,
	[TOMIncompleteReason36mth] [nvarchar](255) NULL,
	[TOMSubmittedDate36mth] [nvarchar](10) NULL,
	[TOMFollowUpResult36mth] [nvarchar](255) NULL,
	[TOMDeathDate36mth] [nvarchar](10) NULL,
	[TOMDeathRelationship36mth] [nvarchar](255) NULL,
	[TOMEndOfTreatmentDate36mth] [nvarchar](10) NULL,
	[TOMTreatmentRegimen36mth] [nvarchar](150) NULL,
	[TOMNonTuberculousMycobacteria36mth] [nvarchar](500) NULL,
	[TOMConversion36mth] [nvarchar](36) NULL,
	[TOMComment36mth] [nvarchar](500) NULL,
	[TOMReported36mth] [nvarchar](10) NULL,
	[TOMReasonExceeds24mths] [nvarchar](50) NULL,
	[WorldRegionName] [nvarchar](50) NULL, 
    [TbService] [nvarchar](150) NULL,
)  
