IF EXISTS (SELECT * 
			FROM master.dbo.sysdatabases 
			WHERE name = 'Labbase2')
ALTER DATABASE Labbase2
SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO

RESTORE DATABASE [Labbase2] 
FROM DISK = N'ADD PATH TO BACKUP FILE HERE'
WITH REPLACE,
NOUNLOAD, STATS = 10
GO