CREATE TABLE [dbo].[UnmatchedSpecimens]
(
	[ReferenceLaboratoryNumber] NVARCHAR(50) NOT NULL PRIMARY KEY,
	[SpecimenDate] DATETIME,
	[SampleType] NVARCHAR(255),
	[LaboratoryName] NVARCHAR(65),
	[ReferenceLaboratory] NVARCHAR(65),
	[Species] VARCHAR(30),
	[INH] NVARCHAR(10),
	[RIF] NVARCHAR(10),
	[PZA] NVARCHAR(10),
	[EMB] NVARCHAR(10),
	[MDR] NVARCHAR(10),
	[AMINO] NVARCHAR(10),
	[QUIN] NVARCHAR(10),
	[XDR] NVARCHAR(10),
	[PatientNhsNumber] NVARCHAR(12),
	[PatientBirthDate] DATETIME,
	[PatientName] NVARCHAR(150),
	[PatientSex] NVARCHAR(1),
	[PatientAddress] NVARCHAR(255),
	[PatientPostcode] NVARCHAR(10),
	[EarliestRecordDate] DATETIME,
	[RegionCode] NVARCHAR(50),
	[Region] NVARCHAR(50),
)
