CREATE TABLE [dbo].[Record_CaseData](
	
	[CaseDataId] [int] IDENTITY(1,1) NOT NULL,

	-- Global (ETS, LTBR, NTBS encompassing) primary key
	[NotificationId] [int] NOT NULL,
	
	[EtsId] [bigint] NULL,
	
	[LtbrId] [nvarchar](50) NULL,
	
	[CaseManager] [nvarchar](101) NULL,
	[Consultant] [nvarchar](255) NULL,
	[HospitalId] [nvarchar](36) NULL,
	[Hospital] [nvarchar](255) NULL,
	[Service] [nvarchar](150) NULL,
	[Age] [tinyint] NULL,
	[Sex] [varchar](30) NULL,
	[UkBorn] [varchar](30) null,
	[EthnicGroup] [varchar](255) NULL,
	[Occupation] [nvarchar](255) NULL,
	[OccupationCategory] [nvarchar] (255) NULL,
	[BirthCountry] [varchar](255) NULL,
	[UkEntryYear] [int] NULL,
	[NoFixedAbode] [nvarchar](30) NULL,

	-- Geographies
	[LocalAuthorityCode] [nvarchar](50) NULL,
	[LocalAuthority] [nvarchar](50) NULL,
	[ResidencePhec] [nvarchar](50) NULL,
	[TreatmentPhec] [nvarchar](50) NULL,
	[Lat] [nvarchar](50) NULL,
	[Long] [nvarchar](50) NULL,

	-- Clinical Details
	[SymptomOnsetDate] date NULL,
	[PresentedDate] date NULL,
	[OnsetToPresentationDays] INT NULL,
	[DiagnosisDate] date NULL,
	[PresentationToDiagnosisDays] INT NULL,
	[StartOfTreatmentDate] date NULL,
	[DiagnosisToTreatmentDays] INT NULL,
	[OnsetToTreatmentDays] INT NULL,
	[HivTestOffered] [nvarchar](255) NULL,
	[SiteOfDisease] [nvarchar](50) NULL,
	[AdultContactsIdentified] [int] NULL,
	[ChildContactsIdentified] [int] NULL,
	[TotalContactsIdentified] [int] NULL,
	[AdultContactsAssessed] [int] NULL,
	[ChildContactsAssessed] [int] NULL,
	[TotalContactsAssessed] [int] NULL,
	[AdultContactsActiveTB] [int] NULL,
	[ChildContactsActiveTB] [int] NULL,
	[TotalContactsActiveTB] [int] NULL,
	[AdultContactsLTBI] [int] NULL,
	[ChildContactsLTBI] [int] NULL,
	[TotalContactsLTBI] [int] NULL,
	[AdultContactsLTBITreat] [int] NULL,
	[ChildContactsLTBITreat] [int] NULL,
	[TotalContactsLTBITreat] [int] NULL,
	[AdultContactsLTBITreatComplete] [int] NULL,
	[ChildContactsLTBITreatComplete] [int] NULL,
	[TotalContactsLTBITreatComplete] [int] NULL,
	[PreviouslyDiagnosed] [varchar](30) NULL,
	[YearsSinceDiagnosis] INT NULL,
	[PreviouslyTreated] [varchar](30) NULL,
	[TreatmentInUk] [varchar](30) NULL,
	[PreviousId] [nvarchar](50) NULL,
	[BcgVaccinated] [varchar](30) NULL,

	-- Risk Factors
	[AnySocialRiskFactor] [varchar](40) NULL,
	[AlcoholMisuse] [varchar](30) NULL,
	[DrugMisuse] [varchar](30) NULL,
	[CurrentDrugMisuse] [varchar](30) NULL,
	[DrugMisuseInLast5Years] [varchar](30) NULL,
	[DrugMisuseMoreThan5YearsAgo] [varchar](30) NULL,
	[Homeless] [varchar](30) NULL,
	[CurrentlyHomeless] [varchar](30) NULL,
	[HomelessInLast5Years] [varchar](30) NULL,
	[HomelessMoreThan5YearsAgo] [varchar](30) NULL,
	[Prison] [varchar](30) NULL,
	[CurrentlyInPrisonOrInPrisonWhenFirstSeen] [varchar](30) NULL,
	[InPrisonInLast5Years] [varchar](30) NULL,
	[InPrisonMoreThan5YearsAgo] [varchar](30) NULL,
	[TravelledOutsideUk] [varchar](30) NULL,
	[ToHowManyCountries] [nvarchar](5) NULL,
	[TravelCountry1] [nvarchar](255) NULL,
	[MonthsTravelled1] [int] NULL,
	[TravelCountry2] [nvarchar](255) NULL,
	[MonthsTravelled2] [int] NULL,
	[TravelCountry3] [nvarchar](255) NULL,
	[MonthsTravelled3] [int] NULL,
	[ReceivedVisitors] [varchar](30) NULL,
	[FromHowManyCountries] [nvarchar](5) NULL,
	[VisitorCountry1] [nvarchar](255) NULL,
	[MonthsVisitorsStayed1] [nvarchar](50) NULL,
	[VisitorCountry2] [nvarchar](255) NULL,
	[MonthsVisitorsStayed2] [nvarchar](50) NULL,
	[VisitorCountry3] [nvarchar](255) NULL,
	[MonthsVisitorsStayed3] [nvarchar](50) NULL,
	[Diabetes] [varchar](30) NULL,
	[HepatitisB] [varchar](30) NULL,
	[HepatitisC] [varchar](30) NULL,
	[ChronicLiverDisease] [varchar](30) NULL,
	[ChronicRenalDisease] [varchar](30) NULL,
	[ImmunoSuppression] [varchar](30) NULL,
	[BiologicalTherapy] [varchar](100) NULL,
	[Transplantation] [varchar](30) NULL,
	[OtherImmunoSuppression] [varchar](30) NULL,
	[CurrentSmoker] [varchar](30) NULL,
	[PostMortemDiagnosis] [varchar](30) NULL,
	[DidNotStartTreatment] [varchar](30) NULL,
	[TreatmentRegimen] NVARCHAR(30) NULL,
	[MdrTreatmentDate] [date] NULL,
	[TreatmentOutcome12months] VARCHAR(30) NULL,
	[TreatmentOutcome24months] VARCHAR(30) NULL,
	[TreatmentOutcome36months] VARCHAR(30) NULL,
	[LastRecordedTreatmentOutcome] VARCHAR(30) NULL,
	[DateOfDeath] DATE NULL,
	[TreatmentEndDate] [date] NULL,

	
	[DataRefreshedAt] [datetime] NOT NULL

	 CONSTRAINT [PK_CaseDataId] PRIMARY KEY CLUSTERED (
		[CaseDataId] ASC
	), 
    CONSTRAINT [FK_Record_CaseData_ToTable] FOREIGN KEY ([NotificationId]) REFERENCES [RecordRegister]([NotificationId])
) ON [PRIMARY]
GO

