CREATE TABLE [dbo].[Record_CaseData](

	[CaseDataId] [int] IDENTITY(1,1) NOT NULL,

	-- Global (ETS, LTBR, NTBS encompassing) primary key
	[NotificationId] [int] NOT NULL,
	[EtsId] [bigint] NULL,
	[LtbrId] [varchar](20) NULL,
	[LinkedNotifications] [varchar](200) NULL,

	[CaseManager] [nvarchar](101) NULL,
	[Consultant] [nvarchar](255) NULL,
	[HospitalId] [varchar](36) NULL,
	[Hospital] [nvarchar](255) NULL,
	[TbService] [nvarchar](150) NULL,
	[NotifyingTbService] [nvarchar](150) NULL,
	[NotifyingTbServiceCode] [nvarchar](15) NULL,
	[NotifyingRegionCode] [nvarchar](15) NULL,
	[LastTransferOutTbService] [nvarchar](150) NULL,
	[LastTransferOutTbServiceCode] [nvarchar](15) NULL,
	[LastTransferOutRegionCode] [nvarchar](15) NULL,
	[SecondaryTbService] [nvarchar](150) NULL,
	[SecondaryTbServiceCode] [nvarchar](15) NULL,
	[SecondaryTbServiceRegionCode] [nvarchar](15) NULL,
	[Age] [tinyint] NULL,
	[Sex] [varchar](10) NULL,
	[UkBorn] [varchar](10) null,
	[EthnicGroup] [varchar](255) NULL,
	[Occupation] [nvarchar](255) NULL,
	[OccupationCategory] [varchar] (255) NULL,
	[BirthCountry] [varchar](255) NULL,
	[WorldRegion] [varchar](50) NULL,
	[UkEntryYear] [int] NULL,
	[NoFixedAbode] [varchar](10) NULL,

	-- Geographies
	[LSOACode] [varchar](10) NULL,
	[LSOAName] [varchar](100) NULL,
	[LocalAuthority] [varchar](50) NULL,
	[ResidencePhec] [varchar](50) NULL,
	[TreatmentPhec] [varchar](50) NULL,
	[AssignedRegion] [varchar](50) NULL,
	[AssignedICB] [varchar](100) NULL,
	[TreatmentICB] [varchar](100) NULL,
	[ResolvedResidenceHPU] [nvarchar](100) NULL,
	[Lat] [nvarchar](50) NULL,
	[Long] [nvarchar](50) NULL,

	-- Clinical Details
	[Symptomatic] [varchar](10) NULL,
	[SymptomOnsetDate] date NULL,
	[FirstPresentationDate] date NULL,
	[OnsetToFirstPresentationDays] INT NULL,
	[TbServiceReferralReceivedDate] date NULL,
	[FirstPresentationToReferralReceivedDays] INT NULL,
	[TbServicePresentationDate] date NULL,
	[ReferralReceivedToTbServiceFirstPresentationDays] INT NULL,	
	[DiagnosisDate] date NULL,
	[PresentationToDiagnosisDays] INT NULL,
	[StartOfTreatmentDate] date NULL,
	[DiagnosisToTreatmentDays] INT NULL,
	[OnsetToTreatmentDays] INT NULL,
	[HivTestOffered] [varchar](30) NULL,
	[Hiv]  [varchar](50) NULL,
	[SiteOfDisease] [varchar](50) NULL,
	[DiseaseSiteList] [varchar](2000) NULL,
	[PostMortemDiagnosis] [varchar](10) NULL,
	[StartedTreatment] [varchar](10) NULL,
	[TreatmentRegimen] [nvarchar](30) NULL,
	[MdrTreatmentDate] date NULL,
	[MdrExpectedDuration] [varchar] (10) NULL,
	[EnhancedCaseManagement] [varchar] (10) NULL,
	[EnhancedCaseManagementLevel] [nvarchar] (10) NULL,
	[FirstPresentationSetting] [nvarchar] (110) NULL,
	[DOTOffered] [varchar] (10) NULL,
	[DOTReceived] [varchar] (20) NULL,
	[VOTOffered] [varchar] (10) NULL,
	[VOTReceived] [varchar] (20) NULL,
	[TestPerformed] [varchar] (10) NULL,
	[SampleTaken] [varchar] (10) NULL,
	[InitialSputumSmearResult] [varchar] (20) NULL,
	[InitialSputumPCRResult] [varchar] (20) NULL,
	[SputumResult] [varchar] (20) NULL,
	[ChestXRayResult] [nvarchar] (100) NULL,
	[ChestCTResult] [nvarchar] (100) NULL,
	[HomeVisitCarriedOut] [varchar] (10) NULL,
	[HomeVisitDate] date NULL,
	[HPTReferenceNumber] VARCHAR(40) NULL,
	[Comments] VARCHAR(2000) NULL,

	--individual disease sites
	[Pulmonary site] VARCHAR(5) NULL,
	[Spine site] VARCHAR(5) NULL,
	[Bone/joint: Other site] VARCHAR(5) NULL,
	[Meningitis site] VARCHAR(5) NULL,
	[CNS: Other site] VARCHAR(5) NULL,
	[Ocular site] VARCHAR(5) NULL,
	[Cryptic disseminated site] VARCHAR(5) NULL,
	[Gastrointestinal/peritoneal site] VARCHAR(5) NULL,
	[Genitourinary site] VARCHAR(5) NULL,
	[Lymph nodes: Intra-thoracic site] VARCHAR(5) NULL,
	[Lymph nodes: Extra-thoracic site] VARCHAR(5) NULL,
	[Laryngeal site] VARCHAR(5) NULL,
	[Miliary site] VARCHAR(5) NULL,
	[Pleural site] VARCHAR(5) NULL,
	[Pericardial site] VARCHAR(5) NULL,
	[Soft tissue/Skin site] VARCHAR(5) NULL,
	[Other extra-pulmonary site] VARCHAR(5) NULL,
	[Other extra-pulmonary site description] VARCHAR(1000) NULL,



	--outcomes
	[TreatmentOutcome12months] [varchar](30) NULL,
	[TreatmentOutcome24months] [varchar](30) NULL,
	[TreatmentOutcome36months] [varchar](30) NULL,
	[LastRecordedTreatmentOutcome] [varchar](30) NULL,
	[TreatmentOutcome12monthsDescriptive] [varchar](250) NULL,
	[TreatmentOutcome24monthsDescriptive] [varchar](250) NULL,
	[TreatmentOutcome36monthsDescriptive] [varchar](250) NULL,
	[LastRecordedTreatmentOutcomeDescriptive] [varchar](250) NULL,
	[DateOfDeath] DATE NULL,
	[TreatmentEndDate] date NULL,
	[TbServiceResponsible12Months] [nvarchar](150) NULL,
	[TbServiceResponsible24Months] [nvarchar](150) NULL,
	[TbServiceResponsible36Months] [nvarchar](150) NULL,


	--contact tracing
	[AdultContactsIdentified] [int] NULL,
	[ChildContactsIdentified] [int] NULL,
	[TotalContactsIdentified] [int] NULL,
	[AdultContactsAssessed] [int] NULL,
	[ChildContactsAssessed] [int] NULL,
	[TotalContactsAssessed] [int] NULL,
	[AdultContactsActiveTB] [int] NULL,
	[ChildContactsActiveTB] [int] NULL,
	[TotalContactsActiveTB] [int] NULL,
	[AdultContactsLTBI] [int] NULL,
	[ChildContactsLTBI] [int] NULL,
	[TotalContactsLTBI] [int] NULL,
	[AdultContactsLTBITreat] [int] NULL,
	[ChildContactsLTBITreat] [int] NULL,
	[TotalContactsLTBITreat] [int] NULL,
	[AdultContactsLTBITreatComplete] [int] NULL,
	[ChildContactsLTBITreatComplete] [int] NULL,
	[TotalContactsLTBITreatComplete] [int] NULL,
	--previous notification
	[PreviouslyDiagnosed] [varchar](10) NULL,
	[YearsSinceDiagnosis] INT NULL,
	[PreviouslyTreated] [varchar](10) NULL,
	[TreatmentInUk] [varchar](10) NULL,
	[PreviousId] [varchar](50) NULL,
	[BcgVaccinated] [varchar](10) NULL,

	-- Risk Factors
	[AnySocialRiskFactor] [varchar](10) NULL,
	[AlcoholMisuse] [varchar](10) NULL,
	[DrugMisuse] [varchar](10) NULL,
	[CurrentDrugMisuse] [varchar](10) NULL,
	[DrugMisuseInLast5Years] [varchar](10) NULL,
	[DrugMisuseMoreThan5YearsAgo] [varchar](10) NULL,
	[Homeless] [varchar](10) NULL,
	[CurrentlyHomeless] [varchar](10) NULL,
	[HomelessInLast5Years] [varchar](10) NULL,
	[HomelessMoreThan5YearsAgo] [varchar](10) NULL,
	[Prison] [varchar](10) NULL,
	[CurrentlyInPrisonOrInPrisonWhenFirstSeen] [varchar](10) NULL,
	[InPrisonInLast5Years] [varchar](10) NULL,
	[InPrisonMoreThan5YearsAgo] [varchar](10) NULL,
	[Smoking] [varchar](10) NULL,
	[CurrentSmoker] [varchar](10) NULL,
	[SmokerInLast5Years] [varchar](10) NULL,
	[SmokerMoreThan5YearsAgo] [varchar](10) NULL,
	[MentalHealth] [varchar](10) NULL,
	[AsylumSeeker] [varchar](10) NULL,
	[ImmigrationDetainee] [varchar](10) NULL,

	--travel and visitor
	[TravelledOutsideUk] [varchar](10) NULL,
	[ToHowManyCountries] [int] NULL,
	[TravelCountry1] [nvarchar](255) NULL,
	[MonthsTravelled1] [int] NULL,
	[TravelCountry2] [nvarchar](255) NULL,
	[MonthsTravelled2] [int] NULL,
	[TravelCountry3] [nvarchar](255) NULL,
	[MonthsTravelled3] [int] NULL,
	[ReceivedVisitors] [varchar](10) NULL,
	[FromHowManyCountries] [int] NULL,
	[VisitorCountry1] [nvarchar](255) NULL,
	[MonthsVisitorsStayed1] [int] NULL,
	[VisitorCountry2] [nvarchar](255) NULL,
	[MonthsVisitorsStayed2] [int] NULL,
	[VisitorCountry3] [nvarchar](255) NULL,
	[MonthsVisitorsStayed3] [int] NULL,
	[Diabetes] [varchar](10)  NULL,
	[HepatitisB] [varchar](10)  NULL,
	[HepatitisC] [varchar](10)  NULL,
	[ChronicLiverDisease] [varchar](10)  NULL,
	[ChronicRenalDisease] [varchar](10)  NULL,
	[ImmunoSuppression] [varchar](10)  NULL,
	[BiologicalTherapy] [varchar](10)  NULL,
	[Transplantation] [varchar](10)  NULL,
	[OtherImmunoSuppression] [varchar](30) NULL,

	-- manual test result summary
	[SmearSummary] [varchar] (30) NULL,
	[CultureSummary] [varchar] (30) NULL,
	[HistologySummary] [varchar] (30) NULL,
	[PCRSummary] [varchar] (30) NULL,
	[LineProbeAssaySummary] [varchar] (30) NULL,

	--mdr details
	[MDRExposureToKnownCase] [varchar] (10) NULL,
	[MDRRelationshipToCase] [nvarchar] (100) NULL,
	[MDRRelatedNotificationId] [int] NULL,
	[MDRDiscussedAtForum] [varchar] (10) NULL,

	-- mbovis details
	[MBovAnimalExposure] [varchar] (10) NULL,
	[MBovKnownCaseExposure] [varchar] (10) NULL,
	[MBovOccupationalExposure] [varchar] (10) NULL,
	[MBovUnpasteurisedMilkConsumption] [varchar] (10) NULL,

	--social context venues
	[SocialContextVenueCount] [int] NULL,
	[SocialContextVenueTypeList] [nvarchar] (2000) NULL,


	[DataRefreshedAt] [datetime] NOT NULL

	 CONSTRAINT [PK_CaseDataId] PRIMARY KEY CLUSTERED (
		[CaseDataId] ASC
	)
) ON [PRIMARY]
GO

