CREATE VIEW [dbo].[ReusableNotification]
	AS
	SELECT 
	  rr.RegisterId						AS ReusableNotificationId
	  ,rr.[NotificationId]
      ,CASE rr.SourceSystem WHEN 'NTBS' THEN rr.NotificationId ELSE NULL END AS [NtbsId]
      ,[EtsId]
      ,[SourceSystem]
      ,[LtbrId]
      ,[NotificationDate]
      ,[CaseManager]
      ,[Consultant]
      ,[HospitalId]
      ,[Hospital]
      ,[TBServiceCode]
	  ,[TbService] AS [Service]
      ,[NhsNumber]
      ,[GivenName] AS [Forename]
      ,[FamilyName] AS [Surname]
      ,[DateOfBirth]
      ,[Age]
      ,[Sex]
      ,[UkBorn]
      ,[EthnicGroup]
      ,[Occupation]
      ,[OccupationCategory]
      ,[BirthCountry]
      ,[UkEntryYear]
      ,[Postcode]
      ,[NoFixedAbode]
      ,[LocalAuthority]
      ,[LocalAuthorityCode]
      ,[ResidencePhecCode]
      ,[ResidencePhec]
      ,[TreatmentPhecCode]
      ,[TreatmentPhec]
      ,[Lat]
      ,[Long]
      ,[SymptomOnsetDate]
	  ,[FirstPresentationDate] AS [PresentedDate]
	  ,COALESCE(OnsetToFirstPresentationDays, 0) + COALESCE(FirstPresentationToTbServicePresentationDays, 0) AS [OnsetToPresentationDays]
      ,[DiagnosisDate]
      ,[PresentationToDiagnosisDays]
      ,[StartOfTreatmentDate]
      ,[DiagnosisToTreatmentDays]
      ,[OnsetToTreatmentDays]
      ,[HivTestOffered]
      ,[SiteOfDisease]
      ,[AdultContactsIdentified]
      ,[ChildContactsIdentified]
      ,[TotalContactsIdentified]
      ,[AdultContactsAssessed]
      ,[ChildContactsAssessed]
      ,[TotalContactsAssessed]
      ,[AdultContactsActiveTB]
      ,[ChildContactsActiveTB]
      ,[TotalContactsActiveTB]
      ,[AdultContactsLTBI]
      ,[ChildContactsLTBI]
      ,[TotalContactsLTBI]
      ,[AdultContactsLTBITreat]
      ,[ChildContactsLTBITreat]
      ,[TotalContactsLTBITreat]
      ,[AdultContactsLTBITreatComplete]
      ,[ChildContactsLTBITreatComplete]
      ,[TotalContactsLTBITreatComplete]
      ,[PreviouslyDiagnosed]
      ,[YearsSinceDiagnosis]
      ,[PreviouslyTreated]
      ,[TreatmentInUk]
      ,[PreviousId]
      ,[BcgVaccinated]
      ,[ClusterId]
      ,[AnySocialRiskFactor] 
      ,[AlcoholMisuse]
      ,[DrugMisuse]
      ,[CurrentDrugMisuse]
      ,[DrugMisuseInLast5Years]
      ,[DrugMisuseMoreThan5YearsAgo]
      ,[Homeless]
      ,[CurrentlyHomeless]
      ,[HomelessInLast5Years]
      ,[HomelessMoreThan5YearsAgo]
      ,[Prison]
      ,[CurrentlyInPrisonOrInPrisonWhenFirstSeen]
      ,[InPrisonInLast5Years]
      ,[InPrisonMoreThan5YearsAgo]
      ,[TravelledOutsideUk]
      ,[ToHowManyCountries]
      ,[TravelCountry1]
      ,[MonthsTravelled1]
      ,[TravelCountry2]
      ,[MonthsTravelled2]
      ,[TravelCountry3]
      ,[MonthsTravelled3]
      ,[ReceivedVisitors]
      ,[FromHowManyCountries]
      ,[VisitorCountry1]
	  ,[MonthsVisitorsStayed1] AS [DaysVisitorsStayed1]
      ,[VisitorCountry2]
	  ,[MonthsVisitorsStayed2] AS [DaysVisitorsStayed2]
      ,[VisitorCountry3]
	  ,[MonthsVisitorsStayed3] AS [DaysVisitorsStayed3]
      ,[Diabetes]
      ,[HepatitisB]
      ,[HepatitisC]
      ,[ChronicLiverDisease]
      ,[ChronicRenalDisease]
      ,[ImmunoSuppression]
      ,[BiologicalTherapy]
      ,[Transplantation]
      ,[OtherImmunoSuppression]
      ,[Smoking] AS CurrentSmoker --we now have time periods in NTBS for smoking, so need to select the 'Yes/No' field rather than CurrentSmoker as previously
      ,[PostMortemDiagnosis]
      ,[DidNotStartTreatment]
      ,[TreatmentRegimen]
      ,[MdrTreatmentDate]
      ,[TreatmentOutcome12months]
      ,[TreatmentOutcome24months]
      ,[TreatmentOutcome36months]
      ,[LastRecordedTreatmentOutcome]
      ,[DateOfDeath]
      ,[TreatmentEndDate]
      ,CASE [SampleTaken] WHEN  'Yes' THEN 'No' WHEN 'No' THEN 'Yes' END AS NoSampleTaken
	  
	  --can't compare these fields because they haven't been (re) developed yet

      ,'No' AS [CulturePositive]
      ,'No result' AS [Species]
      ,NULL [EarliestSpecimenDate]
      ,'No result' AS [DrugResistanceProfile]
      ,'No result' AS [INH]
      ,'No result' AS [RIF]
      ,'No result' AS [EMB]
      ,'No result' AS [PZA]
      ,'No result' AS [AMINO]
      ,'No result' AS [QUIN]
      ,'No result' AS [MDR]
      ,'No result' AS [XDR]
      ,[DataRefreshedAt] 
  FROM [dbo].[RecordRegister] rr
	INNER JOIN [dbo].[Record_PersonalDetails] pd ON pd.NotificationId = rr.NotificationId
	INNER JOIN [dbo].[Record_CaseData] cd ON cd.NotificationId = rr.NotificationId
WHERE rr.Denotified = 0 

